### ISSUE TITLE
wikis are sometimes hard to use, dear friend

### ISSUE THREAD

**Issue by ungoldman** [pdx-towerfall/wiki#1]
they are hard to navigate and impossible to collaborate on

let's just use markdown files

**Comment by ghost** [comment]
while you are absolutely right and I agree with you 100%, I made this thing and there's already stuff in it and so now we have to deal with the reality of my admittedly terrible decision. my apologies! you are great by the way

**Comment by ungoldman** [comment]
wow court I guess that makes sense. sorry it has to be this way but I'll help if I can. and thanks for the compliment :wink:

**Comment by ghost** [comment]
Fine @ngoldman you filthy swine, I have a copy of the wiki locally, if you want to start a new repo of .md docs I'll add the content back in.

You thinking something like https://github.com/sinker/tacofancy

**Comment by ungoldman** [comment]
@courtf i was mainly thinking of using this org to form teams (each team a repo) and a central gh-pages with rules, event times, tournament stuff. does that make sense? in the meantime we can keep collecting lore here
