### ISSUE TITLE
I'd like to play towerfall again

### ISSUE THREAD

**Issue by paulcpederson** [pdx-towerfall/wiki#2]
@pdx-towerfall/players if anybody else wants to I'd really like to play again.

**Comment by ungoldman** [comment]
I will play towerfall

**Comment by paulcpederson** [comment]
/cc @courtf @mannylopez 

sometime this week?

**Comment by ungoldman** [comment]
I'd be willing to host a unisloth tournament at my place at some point too.

**Comment by ungoldman** [comment]
Also I could probably come by tomorrow.

**Comment by JerrySievert** [comment]
i haven't played tower fall since my last day at esri.  i'm in the bay area tomorrow, but would love to play either friday or next week!

**Comment by nikolaswise** [comment]
I would like to play some of this game

**Comment by jyaganeh** [comment]
That's the one where you shoot the arrows and yell at the screen, right?

Maybe after work sometime this week or next?

**Comment by mannylopez** [comment]
I'm in. 

Lunch tomorrow?

For future Towerfall games:
Would folks rather have it at the office or at someone's house? We can even do an after-hours at the office? @paulcpederson's schedule is somewhat tight due to kids and all, so maybe during a lunch hour would be best? What do y'all think?

**Comment by ungoldman** [comment]
I'm okay with offices but EsriPDX has become a place of sadness and some folks would not be able to go there for reasons. I think @paulcpederson sometimes has Thursday evenings to himself if we ever wanted to do an after-hours thing.

**Comment by paulcpederson** [comment]
yeah, generally free thursday evenings, but probably not tomorrow evening, I'm building some stairs.

**Comment by aranasaurus** [comment]
I would be happy to shoot some arrows if this were to take place at a time
that I could attend.

**Comment by ghost** [comment]
He prances once more among the living

![image](https://cloud.githubusercontent.com/assets/1542071/12808593/db3711d0-cacc-11e5-9a24-becd36dbf9d4.png)

**Comment by ghost** [comment]
Is it lunch tomorrow or no? That would work well for me.

**Comment by ungoldman** [comment]
![](http://meme.loqi.me/4fawg_C7.jpg)

See you tomorrow.

**Comment by JerrySievert** [comment]
I can host after work next week.  But no go today. Enjoy!

**Comment by aranasaurus** [comment]
I won't be making it today :( Perhaps next time :)

**Comment by LeChin** [comment]
I'm in!

**Comment by paulcpederson** [comment]
@courtf yes today at lunch sounds like a plan.

**Comment by ungoldman** [comment]
good game everyone.

@aranasaurus now that you are CEO of dark horse maybe you could move the HQ closer to downtown so you can attend games more often? Just throwing that out there

**Comment by aranasaurus** [comment]
Unfortunately we own most of downtown Milwaukie, so that's a hard sell $$-wise. I wish.

**Comment by ungoldman** [comment]
I would argue Portland is the next logical step in a global takeover.

**Comment by ungoldman** [comment]
Or maybe just Foster-Powell.
